"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-25 08:14:59.172240
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("thumb_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_page_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_file_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("orientation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("phash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("low_res", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("platforms", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("niche", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("style_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("script_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("words_per_second", sa.Float(), nullable=False),
        sa.Column("default_voice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_cache",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "idea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("research_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_duration_s", sa.Integer(), nullable=True),
        sa.Column("target_publish_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("folder_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint("format IN ('video','reel')", name="ck_project_format"),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumbnail_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scheduled_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("external_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scene",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("seg_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=True),
        sa.Column("end_s", sa.Float(), nullable=True),
        sa.Column("timing_source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("narration", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("media_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("visual_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("query_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("query_alt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("query_real", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("effect", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("on_screen_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sfx", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("music_cue", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("approved_asset_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "script_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "voice_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("transcript_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scene_asset",
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("crop_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trim_in_s", sa.Float(), nullable=True),
        sa.Column("trim_out_s", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scene.id"],
        ),
        sa.PrimaryKeyConstraint("scene_id", "asset_id"),
    )
    op.create_table(
        "scene_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preview_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("selected", sa.Integer(), nullable=False),
        sa.Column("download_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scene.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_version_id", sa.Integer(), nullable=False),
        sa.Column("seg_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("section", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("est_duration_s", sa.Float(), nullable=True),
        sa.Column("needs_fact_check", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_version_id"],
            ["script_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # Búsqueda global de texto (sección 5.2). Autogenerate no detecta tablas virtuales.
    op.execute("CREATE VIRTUAL TABLE project_fts USING fts5(title, topic, script_text, tags)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS project_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segment")
    op.drop_table("scene_candidate")
    op.drop_table("scene_asset")
    op.drop_table("voice_track")
    op.drop_table("script_version")
    op.drop_table("scene")
    op.drop_table("publication")
    op.drop_table("project")
    op.drop_table("idea")
    op.drop_table("search_cache")
    op.drop_table("operation_log")
    op.drop_table("job")
    op.drop_table("channel")
    op.drop_table("asset")
    # ### end Alembic commands ###
